name: lxHive
mode: production
version: 0.10.0
storage:
    in_use: Mongo
    Mongo:
        host_uri: 'mongodb://127.0.0.1'
        db_name: lxHive
extensions:
    ExtendedQuery:
        class_name: '\API\Extensions\ExtendedQuery\ExtendedQuery'
        enabled: true
xAPI:
    latest_version: 1.0.3
    statement_get_limit: 100
    default_statement_get_format: exact
    supported_versions: [1.0.0, 1.0.1, 1.0.2, 1.0.3]
    supported_auth_scopes:
        'statements/write':
            module: xAPI
            description: 'Write statements'
            inherits: ['attachments']
        'statements/read':
            module: xAPI
            description: 'Read statements'
            inherits: ['attachments']
        'statements/read/mine':
            module: xAPI
            description: 'Read own statements'
            inherits: ['attachments']
        'state':
            module: xAPI
            description: 'Access the State API'
            inherits: []
        'profile':
            module: xAPI
            description: 'Access the Profile API'
            inherits: []
        'define':
            module: xAPI
            description: '(Re)define new Activities'
            inherits: []
        'all/read':
            module: xAPI
            description: 'Full read-only access'
            inherits: ['statements/read/mine', 'attachments', 'state', 'profile', 'attachments']
        'all':
            module: xAPI
            description: 'Full access'
            inherits: ['statements/write', 'statements/read/mine', 'statements/read', 'state', 'define', 'profile', 'all/read', 'attachments']
        'super':
            module: System
            description: 'Administrate the LRS'
            inherits: ['statements/write', 'statements/read/mine', 'statements/read', 'state', 'define', 'profile', 'all/read', 'all', 'attachments']
        'attachments':
            module: System
            description: 'Include attachments'
            inherits: []
    oauth:
        reauthorize_time: 0
        reauthenticate_time: 2592000
        branding:
            enabled: false
            logo_path: null
            header: null
            footer: null
            css_path: null
filesystem:
    exposed_url: /attachments
    in_use: local
    local:
        root_dir: '../storage/files'
slim:
    settings:
        httpVersion: 1.1
        responseChunkSize: 4096
        outputBuffering: append
        determineRouteBeforeAppMiddleware: false
        displayErrorDetails: false
        addContentLengthHeader: true
        routerCacheFile: false
